version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - API__INSTANCE_APP_NAME=test
      - REDIS__HOST=redis
      - REDIS__PORT=6379
    depends_on:
      - redis
    ports:
      - ${API__PORT}:5000
    command: [
      "poetry", "run", "uvicorn", "app:create_app",
      "--host", "0.0.0.0",
      "--port", '5000',
    ]
    networks:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS__PASSWORD}
      - REDIS_PORT=${REDIS__PORT}
      - REDIS_HOST=${REDIS__HOST}
    ports:
      - "${REDIS__PORT}:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis-data:
